# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluationReport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristics',
            name='characteristic',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='coordinates',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='limits_type',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='type',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='responsible',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='groupofcharacteristics',
            name='group_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
