# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processMap', '0001_initial'),
        ('certification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HFCContaminantsRiskMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='certification.RequiredCertificationDocuments')),
            ],
        ),
        migrations.CreateModel(
            name='InvolvedRisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('involved_risk', models.CharField(default='', max_length=50)),
                ('control_method', models.CharField(default='', max_length=50)),
                ('preventive_action', models.CharField(default='', max_length=50)),
                ('process_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processMap.ProcessStep')),
                ('risk_map', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hfcRiskMap.HFCContaminantsRiskMap')),
            ],
        ),
    ]
