# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HFCContaminantsRiskMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='InvolvedRisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('involved_risk', models.CharField(default='', max_length=50)),
                ('control_method', models.CharField(default='', max_length=50)),
                ('preventive_action', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
