# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processMap', '0001_initial'),
        ('hfcRiskMap', '0001_initial'),
        ('certification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='involvedrisk',
            name='process_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processMap.ProcessStep'),
        ),
        migrations.AddField(
            model_name='involvedrisk',
            name='risk_map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hfcRiskMap.HFCContaminantsRiskMap'),
        ),
        migrations.AddField(
            model_name='hfccontaminantsriskmap',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='certification.RequiredCertificationDocuments'),
        ),
    ]
