# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='0000', max_length=140)),
                ('product_description', models.CharField(default='-', max_length=140)),
                ('revision_ECM', models.IntegerField(default=0)),
                ('revision_last', models.DateField(default=0)),
                ('planned_steps', models.CharField(default='-', max_length=140)),
                ('date', models.DateField(default=0)),
                ('closed', models.BooleanField(default=False)),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.EmbracoProfile')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.SupplierProfile')),
            ],
        ),
        migrations.CreateModel(
            name='CertificationApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certification.Certification')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.EmbracoProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(default='-', max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=140)),
                ('unit', models.CharField(default='-', max_length=140)),
                ('measurable', models.BooleanField(default=False)),
                ('resolution', models.FloatField(default=0)),
                ('percentualRnR', models.FloatField(default=0)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.SupplierProfile')),
            ],
        ),
        migrations.CreateModel(
            name='RequiredCertificationDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certification.Certification')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certification.Documents')),
            ],
        ),
    ]
