# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='planned_steps',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='certification',
            name='product_description',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='documents',
            name='document_name',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='measurementsystem',
            name='name',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='measurementsystem',
            name='unit',
            field=models.CharField(default='', max_length=140),
        ),
    ]
