# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0002_auto_20160921_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='date',
            field=models.DateTimeField(default=0),
        ),
    ]
