# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0003_auto_20160926_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='date',
            field=models.DateTimeField(default=''),
        ),
    ]
