# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0004_auto_20160926_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='date',
            field=models.DateField(default=0),
        ),
    ]
