# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('certification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialInformationEmbraco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_batch_delivery', models.IntegerField(default=0)),
                ('multiple_batch', models.IntegerField(default=0)),
                ('stock_level_at_supplier', models.IntegerField(default=0)),
                ('frequency_of_delivery', models.CharField(default='', max_length=50)),
                ('lead_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CommercialInformationSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_batch_delivery', models.IntegerField(default=0)),
                ('multiple_batch', models.IntegerField(default=0)),
                ('stock_level_at_supplier', models.IntegerField(default=0)),
                ('frequency_of_delivery', models.CharField(default='', max_length=50)),
                ('lead_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('date', models.DateField(default=0)),
                ('commercial_information_supplier', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='materialPlanning.CommercialInformationSupplier')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.EmbracoProfile')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialPlanning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('development_responsible_name', models.CharField(default='', max_length=50)),
                ('development_responsible_phone', models.CharField(default='+00 00 0000 0000', max_length=20)),
                ('development_responsible_email', models.EmailField(max_length=254)),
                ('material_planning_responsible_name', models.CharField(default='', max_length=50)),
                ('material_planning_responsible_phone', models.CharField(default='+00 00 0000 0000', max_length=20)),
                ('material_planning_responsible_email', models.EmailField(max_length=254)),
                ('commercial_responsible_name', models.CharField(default='', max_length=50)),
                ('commercial_responsible_phone', models.CharField(default='+00 00 0000 0000', max_length=20)),
                ('commercial_responsible_email', models.EmailField(max_length=254)),
                ('observations', models.CharField(max_length=250, null=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='certification.RequiredCertificationDocuments')),
            ],
        ),
        migrations.AddField(
            model_name='commercialinformationsupplier',
            name='material_planning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materialPlanning.MaterialPlanning'),
        ),
        migrations.AddField(
            model_name='commercialinformationembraco',
            name='material_planning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materialPlanning.MaterialPlanning'),
        ),
    ]
