# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaticContent',
            new_name='PageContents',
        ),
    ]
