# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160912_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontents',
            name='chinese',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='pagecontents',
            name='english',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='pagecontents',
            name='italian',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='pagecontents',
            name='portuguese',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='pagecontents',
            name='slovak',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='pagecontents',
            name='spanish',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
