# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160912_1825'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageContents',
            new_name='PageContent',
        ),
    ]
