# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierprofile',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='supplierprofile',
            name='contactPerson',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='supplierprofile',
            name='country',
            field=models.CharField(default='', max_length=15),
        ),
    ]
