# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20160912_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embracoprofile',
            name='department',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='embracoprofile',
            name='jobTitle',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='supplierprofile',
            name='phoneNumber',
            field=models.CharField(default='+00 00 0000 0000', max_length=20),
        ),
    ]
