# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('certification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('date', models.DateField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PackagingDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='certification.RequiredCertificationDocuments')),
            ],
        ),
        migrations.CreateModel(
            name='PackagingRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packaging_type', models.CharField(default='Type', max_length=20)),
                ('start_date', models.DateField()),
                ('container_type', models.CharField(default='Container Type', max_length=20)),
                ('weight_per_batch', models.FloatField(default=0)),
                ('weight_per_pallet', models.FloatField(default=0)),
                ('sku_qtd_per_pallet', models.IntegerField(default=0)),
                ('container_length', models.FloatField(default=0)),
                ('container_width', models.FloatField(default=0)),
                ('container_height', models.FloatField(default=0)),
                ('pallet_length', models.FloatField(default=0)),
                ('pallet_width', models.FloatField(default=0)),
                ('pallet_height', models.FloatField(default=0)),
                ('container_per_layer', models.IntegerField(default=0)),
                ('parts_per_container', models.IntegerField(default=0)),
                ('layers_per_pallet', models.IntegerField(default=0)),
                ('containers_per_pallet', models.IntegerField(default=0)),
                ('pieces_per_pallet', models.IntegerField(default=0)),
                ('packaging_description', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='packagingDescription.PackagingDescription')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierPackagingDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packaging_type', models.CharField(default='Type', max_length=20)),
                ('start_date', models.DateField()),
                ('container_type', models.CharField(default='Container Type', max_length=20)),
                ('weight_per_batch', models.FloatField(default=0)),
                ('weight_per_pallet', models.FloatField(default=0)),
                ('sku_qtd_per_pallet', models.IntegerField(default=0)),
                ('container_length', models.FloatField(default=0)),
                ('container_width', models.FloatField(default=0)),
                ('container_height', models.FloatField(default=0)),
                ('pallet_length', models.FloatField(default=0)),
                ('pallet_width', models.FloatField(default=0)),
                ('pallet_height', models.FloatField(default=0)),
                ('container_per_layer', models.IntegerField(default=0)),
                ('parts_per_container', models.IntegerField(default=0)),
                ('layers_per_pallet', models.IntegerField(default=0)),
                ('containers_per_pallet', models.IntegerField(default=0)),
                ('pieces_per_pallet', models.IntegerField(default=0)),
                ('packaging_image', models.FileField(upload_to='/static/packaging-images/')),
                ('packaging_description', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='packagingDescription.PackagingDescription')),
            ],
        ),
        migrations.AddField(
            model_name='packagingapproval',
            name='packaging',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='packagingDescription.SupplierPackagingDescription'),
        ),
        migrations.AddField(
            model_name='packagingapproval',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.EmbracoProfile'),
        ),
    ]
