# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oportunity_to_detection', models.CharField(default='', max_length=50)),
                ('detection_probability_by_process_controls', models.CharField(default='', max_length=50)),
                ('typical_control_means', models.CharField(default='', max_length=50)),
                ('classification', models.IntegerField(default=0)),
                ('detection_probability', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FMEA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_or_function', models.CharField(default='', max_length=50)),
                ('potencial_failure_mode', models.CharField(default='', max_length=50)),
                ('potencial_failure_effects', models.CharField(default='', max_length=50)),
                ('severity', models.IntegerField(default=0)),
                ('potencial_cause', models.CharField(default='', max_length=50)),
                ('occurrence', models.IntegerField(default=0)),
                ('current_process_control', models.CharField(default='', max_length=50)),
                ('detection', models.IntegerField(default=0)),
                ('risk_number', models.IntegerField(default=0)),
                ('recommended_actions', models.CharField(default='', max_length=150)),
                ('actions_taken', models.CharField(default='', max_length=150)),
                ('implementation_date', models.DateField()),
                ('severity_result', models.IntegerField(default=0)),
                ('occurrence_result', models.IntegerField(default=0)),
                ('detection_result', models.IntegerField(default=0)),
                ('risk_number_result', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OccurrenceProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_probability', models.CharField(default='', max_length=50)),
                ('occurrence_of_cause', models.CharField(default='', max_length=50)),
                ('classification', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessFMEA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants', models.CharField(default='', max_length=100)),
                ('coordinators', models.CharField(default='', max_length=50)),
                ('coordinator_area', models.CharField(default='', max_length=50)),
                ('issue_date', models.DateField()),
                ('review_number', models.IntegerField(default=0)),
                ('review_date', models.DateField()),
                ('remarks', models.IntegerField(default=0)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='certification.RequiredCertificationDocuments')),
            ],
        ),
        migrations.CreateModel(
            name='SeverityProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect', models.CharField(default='', max_length=50)),
                ('severity_on_product_effect', models.CharField(default='', max_length=50)),
                ('classification', models.IntegerField(default=0)),
                ('product_effect', models.CharField(default='', max_length=50)),
                ('severity_on_product_process', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='fmea',
            name='process_fmea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processFMEA.ProcessFMEA'),
        ),
    ]
