# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessControlParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_parameter', models.CharField(default='Control Parameter', max_length=50)),
                ('tolerance', models.FloatField(default=0)),
                ('control_frequency', models.CharField(default='Monthly', max_length=50)),
                ('sample_size', models.IntegerField(default=1)),
                ('record', models.CharField(default='', max_length=50)),
                ('measurement_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certification.MeasurementSystem')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='certification.RequiredCertificationDocuments')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(default=0)),
                ('step_name', models.CharField(default='Step Name', max_length=50)),
                ('process_map', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processMap.ProcessMap')),
            ],
        ),
        migrations.AddField(
            model_name='processcontrolparameter',
            name='process_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processMap.ProcessStep'),
        ),
    ]
